language: c
os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  homebrew:
    packages:
    - gettext

before_script:
  - ./.travis/autogen.sh

script:
  - ./configure
  - make
  - make check
